# Configuration for the BME280 temperature, humidity and pressure sensor
#
# Used substitutions:
#
# - i2c_pin_sda: SDA pin of the I²C bus for this sensor
# - i2c_pin_scl: SCL pin of the I²C bus for this sensor
# - bme280_i2c_address: I³c address of the sensor
# - bme280_update_interval: update interval of the sensor
# - bme280_offset_temperature: offset of the temperature, e.g. "-1"
# - node_name: name of the device

i2c:
  sda: ${i2c_pin_sda}
  scl: ${i2c_pin_scl}
  frequency: 200kHz

sensor:
  - platform: bme280
    temperature:
      id: t_value
      name: "${node_name} Temperature"
      filters:
        - offset: ${bme280_offset_temperature}
    humidity:
      id: h_value
      name: "${node_name} Humidity"
      filters:
        - offset: ${bme280_offset_humidity}
    pressure:
      id: p_value
      name: "${node_name} Pressure"
    address: ${bme280_i2c_address}
    update_interval: ${bme280_update_interval}
